### ISSUE TITLE
uninitialized constant Int (NameError)

### ISSUE THREAD

**Issue by ExplosiveGM** [rom-rb/rom-rails#101]
rom-core fix this problem in this commit https://github.com/rom-rb/rom/commit/4e2a9222fd6d439bd1e694312a650a72467e5af4
but when i install rom-rails gem i have this error
```
Traceback (most recent call last):
        80: from bin/rails:3:in `<main>'
        79: from bin/rails:3:in `load'
        78: from /home/developer/Projects/backend/bin/spring:15:in `<top (required)>'
        77: from /home/developer/Projects/backend/bin/spring:15:in `require'
        76: from /home/developer/.rvm/gems/ruby-2.5.1/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
        75: from /home/developer/.rvm/gems/ruby-2.5.1/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
        74: from /home/developer/.rvm/gems/ruby-2.5.1/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
        73: from /home/developer/.rvm/gems/ruby-2.5.1/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
        72: from /home/developer/.rvm/gems/ruby-2.5.1/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
        71: from /home/developer/.rvm/gems/ruby-2.5.1/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
        70: from /home/developer/.rvm/gems/ruby-2.5.1/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
        69: from /home/developer/Projects/backend/bin/rails:9:in `<top (required)>'
        68: from /home/developer/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
        67: from /home/developer/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
        66: from /home/developer/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
        65: from /home/developer/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
        64: from /home/developer/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
        63: from /home/developer/.rvm/gems/ruby-2.5.1/gems/railties-5.2.1/lib/rails/commands.rb:18:in `<main>'
        62: from /home/developer/.rvm/gems/ruby-2.5.1/gems/railties-5.2.1/lib/rails/command.rb:46:in `invoke'
        61: from /home/developer/.rvm/gems/ruby-2.5.1/gems/railties-5.2.1/lib/rails/command/base.rb:65:in `perform'
        60: from /home/developer/.rvm/gems/ruby-2.5.1/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        59: from /home/developer/.rvm/gems/ruby-2.5.1/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        58: from /home/developer/.rvm/gems/ruby-2.5.1/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        57: from /home/developer/.rvm/gems/ruby-2.5.1/gems/railties-5.2.1/lib/rails/commands/server/server_command.rb:142:in `perform'
        56: from /home/developer/.rvm/gems/ruby-2.5.1/gems/railties-5.2.1/lib/rails/commands/server/server_command.rb:142:in `tap'
        55: from /home/developer/.rvm/gems/ruby-2.5.1/gems/railties-5.2.1/lib/rails/commands/server/server_command.rb:145:in `block in perform'
        54: from /home/developer/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
        53: from /home/developer/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
        52: from /home/developer/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
        51: from /home/developer/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
        50: from /home/developer/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
        49: from /home/developer/Projects/backend/config/application.rb:19:in `<main>'
        48: from /home/developer/.rvm/gems/ruby-2.5.1/gems/bundler-1.17.1/lib/bundler.rb:114:in `require'
        47: from /home/developer/.rvm/gems/ruby-2.5.1/gems/bundler-1.17.1/lib/bundler/runtime.rb:65:in `require'
        46: from /home/developer/.rvm/gems/ruby-2.5.1/gems/bundler-1.17.1/lib/bundler/runtime.rb:65:in `each'
        45: from /home/developer/.rvm/gems/ruby-2.5.1/gems/bundler-1.17.1/lib/bundler/runtime.rb:76:in `block in require'
        44: from /home/developer/.rvm/gems/ruby-2.5.1/gems/bundler-1.17.1/lib/bundler/runtime.rb:76:in `each'
        43: from /home/developer/.rvm/gems/ruby-2.5.1/gems/bundler-1.17.1/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
        42: from /home/developer/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
        41: from /home/developer/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
        40: from /home/developer/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
        39: from /home/developer/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
        38: from /home/developer/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
        37: from /home/developer/.rvm/gems/ruby-2.5.1/gems/rom-rails-1.2.0/lib/rom-rails.rb:1:in `<main>'
        36: from /home/developer/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
        35: from /home/developer/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
        34: from /home/developer/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
        33: from /home/developer/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
        32: from /home/developer/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
        31: from /home/developer/.rvm/gems/ruby-2.5.1/gems/rom-4.2.0/lib/rom.rb:1:in `<main>'
        30: from /home/developer/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
        29: from /home/developer/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
        28: from /home/developer/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
        27: from /home/developer/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
        26: from /home/developer/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
        25: from /home/developer/.rvm/gems/ruby-2.5.1/gems/rom-core-4.2.0/lib/rom-core.rb:1:in `<main>'
        24: from /home/developer/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
        23: from /home/developer/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
        22: from /home/developer/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
        21: from /home/developer/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
        20: from /home/developer/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
        19: from /home/developer/.rvm/gems/ruby-2.5.1/gems/rom-core-4.2.0/lib/rom/core.rb:11:in `<main>'
        18: from /home/developer/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
        17: from /home/developer/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
        16: from /home/developer/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
        15: from /home/developer/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
        14: from /home/developer/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
        13: from /home/developer/.rvm/gems/ruby-2.5.1/gems/rom-core-4.2.0/lib/rom/relation.rb:16:in `<main>'
        12: from /home/developer/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
        11: from /home/developer/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
        10: from /home/developer/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
         9: from /home/developer/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
         8: from /home/developer/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
         7: from /home/developer/.rvm/gems/ruby-2.5.1/gems/rom-core-4.2.0/lib/rom/relation/curried.rb:9:in `<main>'
         6: from /home/developer/.rvm/gems/ruby-2.5.1/gems/rom-core-4.2.0/lib/rom/relation/curried.rb:10:in `<module:ROM>'
         5: from /home/developer/.rvm/gems/ruby-2.5.1/gems/rom-core-4.2.0/lib/rom/relation/curried.rb:19:in `<class:Relation>'
         4: from /home/developer/.rvm/gems/ruby-2.5.1/gems/rom-core-4.2.0/lib/rom/relation/curried.rb:38:in `<class:Curried>'
         3: from /home/developer/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:42:in `load_missing_constant'
         2: from /home/developer/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:53:in `rescue in load_missing_constant'
         1: from /home/developer/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:8:in `without_bootsnap_cache'
/home/developer/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:53:in `block in load_missing_constant': uninitialized constant Int (NameError)
```

**Comment by ExplosiveGM** [comment]
Sorry, my mistake. I had 
gem 'dry-configurable'
gem 'dry-validation'
in my gemfile.
After updating version, all work fine
