### ISSUE TITLE
Error undefined method `symbolize_keys' in rails v 6rc2

### ISSUE THREAD

**Issue by frostmark** [rom-rb/rom-rails#104]
I added rom-rails to my project on rails 6rc2 version and caught the following error:

```
/Users/markfrost/.rvm/gems/ruby-2.6.3/gems/rom-rails-2.0.0/lib/rom/rails/active_record/configuration.rb:29:in `call': undefined method `symbolize_keys' for #<Array:0x00007fadefc74490> (NoMethodError)
	from /Users/markfrost/.rvm/gems/ruby-2.6.3/gems/rom-rails-2.0.0/lib/rom/rails/railtie.rb:105:in `infer_default_gateway'
	from /Users/markfrost/.rvm/gems/ruby-2.6.3/gems/rom-rails-2.0.0/lib/rom/rails/railtie.rb:89:in `gateways'
	from /Users/markfrost/.rvm/gems/ruby-2.6.3/gems/rom-rails-2.0.0/lib/rom/rails/railtie.rb:73:in `create_configuration'
	from /Users/markfrost/.rvm/gems/ruby-2.6.3/gems/rom-rails-2.0.0/lib/rom/rails/railtie.rb:78:in `create_container'
	from /Users/markfrost/.rvm/gems/ruby-2.6.3/gems/railties-6.0.0.rc2/lib/rails/railtie.rb:190:in `public_send'
	from /Users/markfrost/.rvm/gems/ruby-2.6.3/gems/railties-6.0.0.rc2/lib/rails/railtie.rb:190:in `method_missing'
	from /Users/markfrost/.rvm/gems/ruby-2.6.3/gems/rom-rails-2.0.0/lib/rom/rails/railtie.rb:45:in `block in <class:Railtie>'
	from /Users/markfrost/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0.rc2/lib/active_support/callbacks.rb:429:in `instance_exec'
	from /Users/markfrost/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0.rc2/lib/active_support/callbacks.rb:429:in `block in make_lambda'
	from /Users/markfrost/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0.rc2/lib/active_support/callbacks.rb:201:in `block (2 levels) in halting'
	from /Users/markfrost/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0.rc2/lib/active_support/callbacks.rb:607:in `block (2 levels) in default_terminator'
	from /Users/markfrost/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0.rc2/lib/active_support/callbacks.rb:606:in `catch'
	from /Users/markfrost/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0.rc2/lib/active_support/callbacks.rb:606:in `block in default_terminator'
	from /Users/markfrost/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0.rc2/lib/active_support/callbacks.rb:202:in `block in halting'
	from /Users/markfrost/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0.rc2/lib/active_support/callbacks.rb:514:in `block in invoke_before'
	from /Users/markfrost/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0.rc2/lib/active_support/callbacks.rb:514:in `each'
	from /Users/markfrost/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0.rc2/lib/active_support/callbacks.rb:514:in `invoke_before'
	from /Users/markfrost/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0.rc2/lib/active_support/callbacks.rb:134:in `run_callbacks'
	from /Users/markfrost/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0.rc2/lib/active_support/reloader.rb:88:in `prepare!'
	from /Users/markfrost/.rvm/gems/ruby-2.6.3/gems/railties-6.0.0.rc2/lib/rails/application/finisher.rb:113:in `block in <module:Finisher>'
	from /Users/markfrost/.rvm/gems/ruby-2.6.3/gems/railties-6.0.0.rc2/lib/rails/initializable.rb:32:in `instance_exec'
	from /Users/markfrost/.rvm/gems/ruby-2.6.3/gems/railties-6.0.0.rc2/lib/rails/initializable.rb:32:in `run'
	from /Users/markfrost/.rvm/gems/ruby-2.6.3/gems/railties-6.0.0.rc2/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /Users/markfrost/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
	from /Users/markfrost/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/markfrost/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/markfrost/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/markfrost/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/tsort.rb:347:in `each'
	from /Users/markfrost/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/tsort.rb:347:in `call'
	from /Users/markfrost/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/markfrost/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
	from /Users/markfrost/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
	from /Users/markfrost/.rvm/gems/ruby-2.6.3/gems/railties-6.0.0.rc2/lib/rails/initializable.rb:60:in `run_initializers'
	from /Users/markfrost/.rvm/gems/ruby-2.6.3/gems/railties-6.0.0.rc2/lib/rails/application.rb:363:in `initialize!'
	from /Users/markfrost/oss/to_oss/config/environment.rb:5:in `<main>'


...
```

**Comment by cflipse** [comment]
Hrm..   Yeah, this looks like Rails' change to support multiple database backends breaks the configuration inference.

You can get past this, for now, by explicitly configuring the ROM database:

```
# config/initilizers/rom.rb

ROM::Rails::Railtie.configure do |config|
  config.gateways[:default] = [:sql, ENV.fetch('DATABASE_URL')]
end
```

Where database URL is the full connection URL, along the lines of `postgres://user:pass@localhost/database_name:port`

You'll want to be careful about mixing environments here; I recommend using `dotenv-rails` and setting that envar in a .env.development and .env.test files, so you don't accendentally destroy your development database when running specs...

Working on setting up a better inference mechanism that will handle this change, but that may take some time to get to something clean.

**Comment by frostmark** [comment]
thanks
